#!/bin/bash

alias homeshick='~/.homesick/repos/homeshick/home/.homeshick'
alias cu='cd ..'
alias up='cd ..'
alias up2='cd ../..'
alias up3='cd ../../..'
alias up4='cd ../../../..'
alias up5='cd ../../../../..'
alias up6='cd ../../../../../..'
alias up7='cd ../../../../../../..'
alias up8='cd ../../../../../../../..'
alias up9='cd ../../../../../../../../..'
alias ls='ls --color=auto'
alias ll='ls --color=auto -lh'
